class ReceivedMessage(object):
    """
    A class for message objects in a channel's input queue. These objects are generated by procedure.Receive.
    """

    def __init__(self, message_term):
        """
        :type message_term: (str, str, str, str, int, object)

        format: msg(Sender, SrcRole, Dest, DestRole, Time, Content2)
        """
        (_, self.__sender, self.__src_role, self.__dest, self.__dest_role,
             self.__time, self.__content) = message_term

    @property
    def sender(self):
        return self.__sender

    @property
    def src_role(self):
        return self.__src_role

    @property
    def destination(self):
        return self.__dest

    @property
    def dest_role(self):
        return self.__dest_role

    @property
    def content(self):
        return self.__content



